<?php


return [


    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'DashboardControllers@Dashboard' => 'list-dashboard',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'CityControllers@index' => 'list-cities',
    'CityControllers@edit' => 'edit-city',
    'CityControllers@update' => 'edit-city',
    'CityControllers@fastEdit' => 'edit-city',
    'CityControllers@add' => 'add-city',
    'CityControllers@create' => 'add-city',
    'CityControllers@delete' => 'delete-city',
    'CityControllers@arrange' => 'sort-city',
    'CityControllers@sort' => 'sort-city',
    'CityControllers@charts' => 'charts-city',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    'PageControllers@arrange' => 'sort-page',
    'PageControllers@sort' => 'sort-page',
    'PageControllers@charts' => 'charts-page',
    'PageControllers@uploadImage' => 'uploadImage-page',
    'PageControllers@deleteImage' => 'deleteImage-page',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',
    'ContactUsControllers@charts' => 'charts-contactUs',

    'LogControllers@index' => 'list-logs',
    'LogControllers@fastEdit' => 'edit-log',
    'LogControllers@delete' => 'delete-log',
    'LogControllers@arrange' => 'sort-log',
    'LogControllers@sort' => 'sort-log',
    'LogControllers@charts' => 'charts-log',
    
    'BlockedUsersControllers@index' => 'list-blockedUsers',
    'BlockedUsersControllers@fastEdit' => 'edit-blockedUser',
    'BlockedUsersControllers@delete' => 'delete-blockedUser',
    'BlockedUsersControllers@arrange' => 'sort-blockedUser',
    'BlockedUsersControllers@sort' => 'sort-blockedUser',
    'BlockedUsersControllers@charts' => 'charts-blockedUser',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@panel' => 'list-variables2',
    'VariablesControllers@uploadImage' => 'edit-variable2',
    'VariablesControllers@deleteImage' => 'edit-variable2',

    'MembershipControllers@index' => 'list-memberships',
    'MembershipControllers@edit' => 'edit-membership',
    'MembershipControllers@update' => 'edit-membership',
    'MembershipControllers@fastEdit' => 'edit-membership',
    'MembershipControllers@add' => 'add-membership',
    'MembershipControllers@create' => 'add-membership',
    'MembershipControllers@delete' => 'delete-membership',
    'MembershipControllers@arrange' => 'sort-membership',
    'MembershipControllers@sort' => 'sort-membership',
    'MembershipControllers@charts' => 'charts-membership',

    'FeatureControllers@index' => 'list-features',
    'FeatureControllers@edit' => 'edit-feature',
    'FeatureControllers@update' => 'edit-feature',
    'FeatureControllers@fastEdit' => 'edit-feature',
    'FeatureControllers@add' => 'add-feature',
    'FeatureControllers@create' => 'add-feature',
    'FeatureControllers@delete' => 'delete-feature',
    'FeatureControllers@arrange' => 'sort-feature',
    'FeatureControllers@sort' => 'sort-feature',
    'FeatureControllers@charts' => 'charts-feature',

    'ConditionControllers@index' => 'list-conditions',
    'ConditionControllers@edit' => 'edit-condition',
    'ConditionControllers@update' => 'edit-condition',
    'ConditionControllers@fastEdit' => 'edit-condition',
    'ConditionControllers@add' => 'add-condition',
    'ConditionControllers@create' => 'add-condition',
    'ConditionControllers@delete' => 'delete-condition',
    'ConditionControllers@arrange' => 'sort-condition',
    'ConditionControllers@sort' => 'sort-condition',
    'ConditionControllers@charts' => 'charts-condition',

    'FieldControllers@index' => 'list-fields',
    'FieldControllers@edit' => 'edit-field',
    'FieldControllers@update' => 'edit-field',
    'FieldControllers@fastEdit' => 'edit-field',
    'FieldControllers@add' => 'add-field',
    'FieldControllers@create' => 'add-field',
    'FieldControllers@delete' => 'delete-field',
    'FieldControllers@arrange' => 'sort-field',
    'FieldControllers@sort' => 'sort-field',
    'FieldControllers@charts' => 'charts-field',

    'OrderControllers@index' => 'list-orders',
    'OrderControllers@softDelete' => 'delete-order',
    'OrderControllers@delete' => 'delete-order',
    'OrderControllers@fastEdit' => 'edit-order',
    'OrderControllers@changeStatus' => 'edit-order',
    'OrderControllers@newMember' => 'edit-order',

    'UserCardControllers@index' => 'list-user-cards',
    'UserCardControllers@fastEdit' => 'edit-user-card',
    'UserCardControllers@delete' => 'delete-user-card',
    'UserCardControllers@charts' => 'charts-user-card',

  
];
