<?php


return [


    'HomeControllers@index' => 'general',
    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'DashboardControllers@Dashboard' => 'list-dashboard',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'TopMenuControllers@index' => 'list-topMenus',
    'TopMenuControllers@edit' => 'edit-topMenu',
    'TopMenuControllers@update' => 'edit-topMenu',
    'TopMenuControllers@fastEdit' => 'edit-topMenu',
    'TopMenuControllers@add' => 'add-topMenu',
    'TopMenuControllers@create' => 'add-topMenu',
    'TopMenuControllers@delete' => 'delete-topMenu',
    'TopMenuControllers@arrange' => 'sort-topMenu',
    'TopMenuControllers@sort' => 'sort-topMenu',
    'TopMenuControllers@charts' => 'charts-topMenu',

    'BottomMenuControllers@index' => 'list-bottomMenus',
    'BottomMenuControllers@edit' => 'edit-bottomMenu',
    'BottomMenuControllers@update' => 'edit-bottomMenu',
    'BottomMenuControllers@add' => 'add-bottomMenu',
    'BottomMenuControllers@fastEdit' => 'edit-bottomMenu',
    'BottomMenuControllers@create' => 'add-bottomMenu',
    'BottomMenuControllers@delete' => 'delete-bottomMenu',
    'BottomMenuControllers@arrange' => 'sort-bottomMenu',
    'BottomMenuControllers@sort' => 'sort-bottomMenu',
    'BottomMenuControllers@charts' => 'charts-bottomMenu',

    'AdvantageControllers@index' => 'list-advantages',
    'AdvantageControllers@edit' => 'edit-advantage',
    'AdvantageControllers@fastEdit' => 'edit-advantage',
    'AdvantageControllers@update' => 'edit-advantage',
    'AdvantageControllers@add' => 'add-advantage',
    'AdvantageControllers@create' => 'add-advantage',
    'AdvantageControllers@delete' => 'delete-advantage',
    'AdvantageControllers@arrange' => 'sort-advantage',
    'AdvantageControllers@sort' => 'sort-advantage',
    'AdvantageControllers@charts' => 'charts-advantage',

    'BenefitControllers@index' => 'list-benefits',
    'BenefitControllers@edit' => 'edit-benefit',
    'BenefitControllers@update' => 'edit-benefit',
    'BenefitControllers@fastEdit' => 'edit-benefit',
    'BenefitControllers@add' => 'add-benefit',
    'BenefitControllers@create' => 'add-benefit',
    'BenefitControllers@delete' => 'delete-benefit',
    'BenefitControllers@arrange' => 'sort-benefit',
    'BenefitControllers@sort' => 'sort-benefit',
    'BenefitControllers@charts' => 'charts-benefit',

    'CityControllers@index' => 'list-cities',
    'CityControllers@edit' => 'edit-city',
    'CityControllers@update' => 'edit-city',
    'CityControllers@fastEdit' => 'edit-city',
    'CityControllers@add' => 'add-city',
    'CityControllers@create' => 'add-city',
    'CityControllers@delete' => 'delete-city',
    'CityControllers@arrange' => 'sort-city',
    'CityControllers@sort' => 'sort-city',
    'CityControllers@charts' => 'charts-city',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    'PageControllers@arrange' => 'sort-page',
    'PageControllers@sort' => 'sort-page',
    'PageControllers@charts' => 'charts-page',
    'PageControllers@uploadImage' => 'uploadImage-page',
    'PageControllers@deleteImage' => 'deleteImage-page',

    'SliderControllers@index' => 'list-sliders',
    'SliderControllers@edit' => 'edit-slider',
    'SliderControllers@update' => 'edit-slider',
    'SliderControllers@fastEdit' => 'edit-slider',
    'SliderControllers@add' => 'add-slider',
    'SliderControllers@create' => 'add-slider',
    'SliderControllers@delete' => 'delete-slider',
    'SliderControllers@arrange' => 'sort-slider',
    'SliderControllers@sort' => 'sort-slider',
    'SliderControllers@charts' => 'charts-slider',
    'SliderControllers@uploadImage' => 'uploadImage-slider',
    'SliderControllers@deleteImage' => 'deleteImage-slider',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',
    'ContactUsControllers@charts' => 'charts-contactUs',

    'PhotoControllers@index' => 'list-photos',
    'PhotoControllers@edit' => 'edit-photo',
    'PhotoControllers@update' => 'edit-photo',
    'PhotoControllers@fastEdit' => 'edit-photo',
    'PhotoControllers@add' => 'add-photo',
    'PhotoControllers@create' => 'add-photo',
    'PhotoControllers@delete' => 'delete-photo',
    'PhotoControllers@arrange' => 'sort-photo',
    'PhotoControllers@sort' => 'sort-photo',
    'PhotoControllers@charts' => 'charts-photo',
    'PhotoControllers@uploadImage' => 'uploadImage-photo',
    'PhotoControllers@deleteImage' => 'deleteImage-photo',

    'FileControllers@index' => 'list-files',
    'FileControllers@edit' => 'edit-file',
    'FileControllers@update' => 'edit-file',
    'FileControllers@add' => 'add-file',
    'FileControllers@create' => 'add-file',
    'FileControllers@delete' => 'delete-file',
    'FileControllers@arrange' => 'sort-file',
    'FileControllers@fastEdit' => 'edit-file',
    'FileControllers@sort' => 'sort-file',
    'FileControllers@charts' => 'charts-file',
    'FileControllers@uploadImage' => 'uploadImage-file',
    'FileControllers@deleteImage' => 'deleteImage-file',

    'LogControllers@index' => 'list-logs',
    'LogControllers@fastEdit' => 'edit-log',
    'LogControllers@delete' => 'delete-log',
    'LogControllers@arrange' => 'sort-log',
    'LogControllers@sort' => 'sort-log',
    'LogControllers@charts' => 'charts-log',

    'BlockedUsersControllers@index' => 'list-blockedUsers',
    'BlockedUsersControllers@fastEdit' => 'edit-blockedUser',
    'BlockedUsersControllers@delete' => 'delete-blockedUser',
    'BlockedUsersControllers@arrange' => 'sort-blockedUser',
    'BlockedUsersControllers@sort' => 'sort-blockedUser',
    'BlockedUsersControllers@charts' => 'charts-blockedUser',

    'OrderControllers@index' => 'list-orders',
    'OrderControllers@softDelete' => 'delete-order',
    'OrderControllers@delete' => 'delete-order',
    'OrderControllers@fastEdit' => 'edit-order',
    'OrderControllers@changeStatus' => 'edit-order',
    'OrderControllers@charts' => 'charts-order',

    'OrderControllers@trashes' => 'list-trashes',
    'OrderControllers@softDelete' => 'delete-order',
    'OrderControllers@delete' => 'delete-order',
    'OrderControllers@fastEdit' => 'edit-order',
    'OrderControllers@changeStatus' => 'edit-order',
    'OrderControllers@charts' => 'charts-order',

    'OrderControllers@newOrders' => 'list-newOrders',
    'OrderControllers@softDelete' => 'delete-newOrder',
    'OrderControllers@delete' => 'delete-newOrder',
    'OrderControllers@fastEdit' => 'edit-newOrder',
    'OrderControllers@changeStatus' => 'edit-newOrder',
    'OrderControllers@charts' => 'charts-newOrder',

    'OrderControllers@sentOrders' => 'list-sentOrders',
    'OrderControllers@softDelete' => 'delete-sentOrder',
    'OrderControllers@delete' => 'delete-sentOrder',
    'OrderControllers@fastEdit' => 'edit-sentOrder',
    'OrderControllers@changeStatus' => 'edit-sentOrder',
    'OrderControllers@charts' => 'charts-sentOrder',

    'OrderControllers@delayedOrders' => 'list-delayedOrders',
    'OrderControllers@softDelete' => 'delete-delayedOrder',
    'OrderControllers@delete' => 'delete-delayedOrder',
    'OrderControllers@fastEdit' => 'edit-delayedOrder',
    'OrderControllers@changeStatus' => 'edit-delayedOrder',
    'OrderControllers@charts' => 'charts-delayedOrder',

    'OrderControllers@receivedOrders' => 'list-receivedOrders',
    'OrderControllers@softDelete' => 'delete-receivedOrder',
    'OrderControllers@delete' => 'delete-receivedOrder',
    'OrderControllers@fastEdit' => 'edit-receivedOrder',
    'OrderControllers@changeStatus' => 'edit-receivedOrder',
    'OrderControllers@charts' => 'charts-receivedOrder',

    'OrderControllers@unRepliedOrders' => 'list-unRepliedOrders',
    'OrderControllers@softDelete' => 'delete-unRepliedOrder',
    'OrderControllers@delete' => 'delete-unRepliedOrder',
    'OrderControllers@fastEdit' => 'edit-unRepliedOrder',
    'OrderControllers@changeStatus' => 'edit-unRepliedOrder',
    'OrderControllers@charts' => 'charts-unRepliedOrder',

    'OrderControllers@cancelledOrders' => 'list-cancelledOrders',
    'OrderControllers@softDelete' => 'delete-cancelledOrder',
    'OrderControllers@delete' => 'delete-cancelledOrder',
    'OrderControllers@fastEdit' => 'edit-cancelledOrder',
    'OrderControllers@changeStatus' => 'edit-cancelledOrder',
    'OrderControllers@charts' => 'charts-cancelledOrder',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@panel' => 'list-variables2',
    'VariablesControllers@uploadImage' => 'edit-variable2',
    'VariablesControllers@deleteImage' => 'edit-variable2',

    


];
